      - name: GUARDAR Y SUBIR CAMBIOS
        run: |
          git config --local user.email "victor@centro-mando.com"
          git config --local user.name "Victorfs978-Bot"
          # Si el archivo no existe, lo crea vacío para evitar errores
          touch lista_canales.txt 
          git add lista_canales.txt
          git commit -m "Actualización: $(date)" || echo "Nada nuevo"
          git push
