name: Bot_F12_Victor_Ofensiva
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Se ejecuta cada hora

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Herramientas F12 (Crítico)
        run: |
          pip install requests playwright
          playwright install chromium
          playwright install-deps

      - name: Ejecutar Bot Maestro
        run: python bot.py

      - name: GUARDAR Y SUBIR CAMBIOS
        run: |
          git config --local user.email "bot@futbol.com"
          git config --local user.name "Victor-Bot"
          git add lista_canales.txt
          git commit -m "Actualización F12: $(date)" || exit 0
          git push origin main
          
